const services=[['Washing','Deep cleaning for everyday clothes','♧','Freshen up everyday garments with our washing service. Tell us about your items and any special care requirements when booking.'],['Ironing & Pressing','Crisp, wrinkle-free clothes','♨','Bring a crisp finish to shirts, trousers and everyday clothing. Ask our team about ironing and pressing for your garments.'],['Dry Cleaning','Professional care for delicate fabrics','♧','Request care for suits, dresses and delicate garments. Our team will confirm the appropriate treatment after reviewing your items.'],['Carpet & Curtain Cleaning','Deep cleaning for your home','▥','Book cleaning for carpets and curtains. Share the material, dimensions and a photo on WhatsApp so we can discuss your needs and quote.'],['Shoes Cleaning','Fresh, clean and ready to wear','♧','Ask about cleaning for your shoes. Send a photo and the material type for a suitable quote and care advice.'],['Special Care','Blankets, bed sheets & more','▤','Arrange care for blankets, bed sheets, comforters and other home textiles. Let us know sizes and quantities when requesting a quote.']];
const dialog=document.querySelector('#service-dialog');services.forEach((s,i)=>{const card=document.createElement('article');card.className='service-card';card.innerHTML=`<img src="assets/service${i}-hd.webp" alt="${s[0]}" loading="lazy"><div class="service-icon" aria-hidden="true">${s[2]}</div><h3>${s[0]}</h3><p>${s[1]}</p>`;document.querySelector('#service-grid').append(card)});
dialog.querySelector('.close').onclick=()=>dialog.close();dialog.querySelector('a').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});const menu=document.querySelector('.menu');menu.onclick=()=>{const open=document.querySelector('nav').classList.toggle('open');menu.setAttribute('aria-expanded',String(open))};document.querySelectorAll('nav a').forEach(a=>a.onclick=()=>{document.querySelector('nav').classList.remove('open');menu.setAttribute('aria-expanded','false')});document.querySelector('#year').textContent=new Date().getFullYear();
const navLinks=[...document.querySelectorAll('nav a')];const sections=navLinks.map(a=>document.querySelector(a.getAttribute('href'))).filter(Boolean);const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting){navLinks.forEach(a=>{const active=a.getAttribute('href')==='#'+entry.target.id;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}}},{rootMargin:'-15% 0px -65% 0px',threshold:0});sections.forEach(section=>observer.observe(section));navLinks[0].classList.add('active');navLinks[0].setAttribute('aria-current','location');

const contactRail=document.querySelector('.mobile-contact');
const contactToggle=contactRail.querySelector('.contact-toggle');
const contactPanel=document.querySelector('#mobile-contact-panel');
function setContactOpen(open){contactRail.classList.toggle('open',open);contactToggle.setAttribute('aria-expanded',String(open));contactToggle.setAttribute('aria-label',open?'Close booking and call buttons':'Open booking and call buttons');contactPanel.hidden=!open;contactPanel.inert=!open;}
setContactOpen(false);
contactToggle.addEventListener('click',()=>setContactOpen(contactToggle.getAttribute('aria-expanded')!=='true'));
document.addEventListener('click',e=>{if(!contactRail.contains(e.target))setContactOpen(false)});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&contactToggle.getAttribute('aria-expanded')==='true'){setContactOpen(false);contactToggle.focus()}});
contactPanel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>setContactOpen(false)));
