const laundryPrices={
'Washing & Ironing':[['Trouser',4],['Shirt',4],['T-Shirt',4],['Sweater — Big',6],['Sweater — Small',4],['Overall',10],['Kandura',6],['Ghutra',5],['Vest',2],['Tie',5],['Lungi',4],['Underwear',2],['Shorts',3],['Socks',2],['Cap',3],['Mini Skirt',8],['Long Skirt',12],['Long Dress',12],['Bra',2],['Brassiere',4],['Sandal — 1 Pair',10],['Napkin',1.5],['Face Towel',2],['Bath Towel — Big',5],['Bath Towel — Small',3],['Bath Robe',10],['Door Mat',5],['Bed Cover',8],['Bed Sheet — Big',8],['Bed Sheet — Small',5],['Pillow Case — Big',2],['Pillow Case — Small',2],['Table Cloth — Small',2],['Table Cloth — Big',4],['Blanket',20],['Blanket — Small',15],['Blanket — Big',25],['Sofa Cover',20],['Curtain — Big',30],['Curtain — Small',20]],
'Dry Cleaning':[['Suit',20],['Jacket',14],['Trouser',6],['Shirt',5],['T-Shirt',5],['Dishdasha',10],['Kandura',10],['Ghutra',8],['Salwar Kameez — 3 Pieces',15],['Abaya',10],['Shela',5],['Saree',15],['Blouse',5],['Silk Blouse',6],['Fancy Dress',15],['Nighty Dress',15],['Sweater — Big',8],['Sweater — Small',5]],
'Ironing':[['Trouser',2],['Shirt',2],['T-Shirt',2],['Sweater',2],['Kandura',4],['Ghutra',4],['Overall',3],['Lungi',2],['Abaya',5],['Shela',3],['Saree',5],['Dress',10],['Bed Cover',4],['Bed Sheet — Big',5],['Bed Sheet — Small',4],['Pillow Case',2]]};
let selectedCategory='Washing & Ironing';const basket=new Map();const money=n=>'AED '+n.toFixed(2);const tabs=document.querySelector('#price-tabs');Object.keys(laundryPrices).forEach(category=>{const b=document.createElement('button');b.type='button';b.textContent=category;b.setAttribute('role','tab');b.onclick=()=>{selectedCategory=category;renderPrices()};tabs.append(b)});
function renderPrices(){[...tabs.children].forEach(b=>{const on=b.textContent===selectedCategory;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on))});const term=document.querySelector('#price-search').value.toLowerCase();const rows=laundryPrices[selectedCategory].filter(([name])=>name.toLowerCase().includes(term));document.querySelector('#price-table tbody').replaceChildren();for(const [name,price]of rows){const tr=document.createElement('tr');const key=selectedCategory+'|'+name;tr.innerHTML=`<td>${name}</td><td>${money(price)}</td><td><div class="quantity"><button type="button" aria-label="Remove one ${name}">−</button><output>${basket.get(key)?.quantity||0}</output><button type="button" aria-label="Add one ${name}">+</button></div></td>`;const buttons=tr.querySelectorAll('button');buttons[0].onclick=()=>changeQuantity(key,name,price,-1);buttons[1].onclick=()=>changeQuantity(key,name,price,1);document.querySelector('#price-table tbody').append(tr)}document.querySelector('#price-empty').hidden=rows.length>0;document.querySelector('#price-table caption').textContent=selectedCategory+' · Prices in AED';renderEstimate()}
function changeQuantity(key,name,price,delta){const quantity=Math.max(0,(basket.get(key)?.quantity||0)+delta);if(quantity)basket.set(key,{name,category:selectedCategory,price,quantity});else basket.delete(key);renderPrices()}
function renderEstimate(){let total=0,count=0;const list=document.querySelector('#estimate-items');list.replaceChildren();basket.forEach(item=>{total+=item.price*item.quantity;count+=item.quantity;const li=document.createElement('li');li.textContent=`${item.quantity} × ${item.name} (${item.category}) — ${money(item.price*item.quantity)}`;list.append(li)});document.querySelector('#estimate-total').textContent=money(total);document.querySelector('#estimate-count').textContent=count+' items selected';document.querySelector('#estimate-book').disabled=count===0;document.querySelector('#estimate-clear').disabled=count===0;}
document.querySelector('#price-search').oninput=renderPrices;document.querySelector('#estimate-clear').onclick=()=>{basket.clear();renderPrices()};document.querySelector('#estimate-book').onclick=()=>{let total=0;const lines=[];basket.forEach(item=>{total+=item.price*item.quantity;lines.push(`${item.quantity} x ${item.name} (${item.category}): ${money(item.price*item.quantity)}`)});const message='Hello Noor Al Sharq Laundry, I would like to request a pickup for:\n'+lines.join('\n')+'\nEstimated total: '+money(total)+'\nPlease confirm the final price and pickup availability.';window.open('https://wa.me/971569005236?text='+encodeURIComponent(message),'_blank','noopener,noreferrer')};renderPrices();
